version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
configuration:
  - Release
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack ./lib/Fulib/Fulib.csproj
  - cmd: appveyor PushArtifact ./lib/Fulib/bin/Release/Fulib.1.0.3.nupkg
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # - cmd: dotnet restore ./tests/Fulib.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests
  - cmd: dotnet xunit --fx-version 2.0.0
on_finish :
deploy:
  provider: NuGet
  api_key:
    secure: Pr85YtvKtnrh7tWYGq3ALBLsfUPowAmbMmBxfuSI6eQwxgDTCeqm+o5Gy8fDYj0Z
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/